export class UserScores {
  initial_elo_rating!: number
  elo_rating!: number
  topic_ratings!: {
    array?: number
    math?: number
    depthFirstSearch?: number
    breadthFirstSearch?: number
    unionFind?: number
    geometry?: number
    dynamicProgramming?: number
    binaryIndexedTree?: number
    orderedSet?: number
    binarySearch?: number
    greedy?: number
    heapPriorityQueue?: number
    string?: number
    backtracking?: number
    numberTheory?: number
    bitManipulation?: number
    bitmask?: number
    graph?: number
    topologicalSort?: number
    enumeration?: number
    matrix?: number
    prefixSum?: number
    hashTable?: number
    tree?: number
    simulation?: number
    sorting?: number
    stack?: number
    queue?: number
    monotonicStack?: number
    monotonicQueue?: number
    segmentTree?: number
    counting?: number
    shortestPath?: number
    recursion?: number
    stringMatching?: number
    slidingWindow?: number
    memoization?: number
    gameTheory?: number
    divideAndConquer?: number
    combinatorics?: number
    trie?: number
    twoPointers?: number
    rollingHash?: number
    hashFunction?: number
    sweepLine?: number
    suffixArray?: number
    eulerianCircuit?: number
    linkedList?: number
    doublyLinkedList?: number
    minimumSpanningTree?: number
    stronglyConnectedComponent?: number
    binarySearchTree?: number
    binaryTree?: number
    design?: number
    probabilityAndStatistics?: number
    dataStream?: number
    brainteaser?: number
    mergeSort?: number
    sort?: number
    randomized?: number
    biconnectedComponent?: number
    interactive?: number
    quickselect?: number
    radixSort?: number
    iterator?: number
    countingSort?: number
  } | {}
  approaches_score!: number
  days_logged_in!: string[]
  consistency_score!: number
  edge_case_score!: number
  total_score!: number
}
